#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            systemctl stop sonarr.service
            systemctl disable sonarr.service
        fi

        SERVICE_XPATH_NAME="sonarr"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! getent passwd sonarr >/dev/null 2>&1; then
            echo "Adding sonarr user..."
            adduser --quiet \
                    --system \
                    --group \
                    --disabled-password \
                    sonarr
        else
            echo "sonarr user already exists."
        fi

        if [ ! -d "/opt/Sonarr" ]; then
            echo "Downloading latest files..."
            cd /opt
            wget -q "http://update.nzbdrone.com/v2/master/mono/NzbDrone.master.tar.gz"
            echo "Downloading complete, extracting files..."
            tar -zxvf NzbDrone.master.tar.gz
            rm -Rf NzbDrone.master.tar.gz
            mv /opt/NzbDrone /opt/Sonarr
            chown sonarr:sonarr /opt/Sonarr -R
        fi

        if [ -f "/var/run/sonarr/sonarr.pid" ]; then
            echo "Cleaning old pid file..."
            rm -Rf /var/run/sonarr/sonarr.pid
        fi

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"

            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "showtab" "0"
            omv_config_add_element "${SERVICE_XPATH}" "port" "8989"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
